### ISSUE TITLE
tried with 4s on iOS 9.3.5 but can`t fix "Code:0x9, Description: security policy error" problem

### ISSUE THREAD

**Issue by r0ysue** [Proteas/native-lldb-for-ios#1]
# cat ent.xml
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>com.apple.springboard.debugapplications</key>
        <true/>
        <key>get-task-allow</key>
        <true/>
        <key>task_for_pid-allow</key>
        <true/>
        <key>run-unsigned-code</key>
        <true/>
</dict>
</plist>

# ldid -Sent.xml /Applications/MobileSafari.app/MobileSafari

# lldb  /Applications/MobileSafari.app/MobileSafari
(lldb) target create "/Applications/MobileSafari.app/MobileSafari"
Current executable set to '/Applications/MobileSafari.app/MobileSafari' (armv7).
(lldb) b UIApplicationMain
Breakpoint 1: no locations (pending).
WARNING:  Unable to resolve breakpoint to any actual locations.
(lldb) r
[DEBUG]--->/Users/Proteas/Proteas/opensource/llvm-llvm/llvm-ios.svn/tools/lldb/source/Host/macosx/Host.mm:1571:LaunchProcessSpringBoard - Fail to Launch App with Bundle ID: com.apple.mobilesafari, Code:0x9, Description: security policy error.
error: (os/kern) failure
(lldb)

**Comment by Proteas** [comment]
REF: https://iosgods.com/topic/59064-new-lldb-debugger-for-all-ios-versions/
